SELECT TABLESPACE_NAME, BYTES/1024/2024 MB, FILE_NAME 
FROM DBA_DATA_FILES;

SELECT USERNAME, DEFAULT_TABLESPACE,
        CREATED, LAST_LOGIN
FROM DBA_USERS
WHERE USERNAME = USER;


SELECT TABLESPACE_NAME, TABLE_NAME
FROM USER_TABLES;